"""file table updated

Revision ID: 2bc84a9c78bc
Revises: 933985f6331b
Create Date: 2026-05-14 16:26:02.200985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc84a9c78bc'
down_revision: Union[str, Sequence[str], None] = '933985f6331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'error_message')
    op.drop_column('files', 'extracted_text')
    op.drop_column('files', 'file_size')
    op.drop_column('files', 'file_type')
    op.drop_column('files', 'storage_path')
    # ### end Alembic commands ###
