"""added storage name

Revision ID: 9e8fbbbc45e7
Revises: 2bc84a9c78bc
Create Date: 2026-05-15 08:32:26.830606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8fbbbc45e7'
down_revision: Union[str, Sequence[str], None] = '2bc84a9c78bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'files', ['storage_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'storage_name')
    # ### end Alembic commands ###
